export const LIST_PRODUCTS ="LIST_PRODUCTS";
export const ADD_TO_CART ="ADD_TO_CART";
export const CHANGE_MSG ="CHANGE_MSG";
export const DELETE_CART_ITEM ="DELETE_CART_ITEM";
export const UPDATE_QUANTITY ="UPDATE_QUANTITY";